module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  breakpoint: 0
  system: 0
  toolbar: 0
  user: 0
  config_installer: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
profile: config_installer
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
