module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  block: 0
  breakpoint: 0
  config: 0
  dblog: 0
  default_content: 0
  dolebas_config: 0
  dolebas_default_content: 0
  dolebas_payments: 0
  dolebas_player: 0
  dolebas_publisher: 0
  dolebas_uploader: 0
  dynamic_page_cache: 0
  eva: 0
  exclude_node_title: 0
  field: 0
  field_ui: 0
  filter: 0
  hal: 0
  jsonapi: 0
  link: 0
  menu_link_content: 0
  menu_ui: 0
  node: 0
  page_cache: 0
  path: 0
  require_login: 0
  rest: 0
  serialization: 0
  system: 0
  text: 0
  toolbar: 0
  user: 0
  views: 0
  views_bootstrap: 0
  views_ui: 0
  config_installer: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  bootstrap: 0
  dolebas_subtheme: 0
profile: config_installer
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
